/**
 * Discovery 03 and 04, where the business comes from and how a deal actually moves.
 *
 * Module 03 reconstructs the arrival mix from settled evidence rather than from the channel
 * story the client tells, because a funnel built against a route that produces nothing is
 * aimed at nothing. Module 04 walks one real deal end to end, step by step, and records what
 * each step runs on and who holds it. Together they decide two things: whether this is an
 * acquisition build or a retention build, and where the work currently sits in one person.
 *
 * Nothing here asserts a Finance OS fact, a price, a turnaround or an outcome. Where a step
 * is regulated, the question records the client practice and the note routes it to their own
 * adviser. The instrument describes; it does not rule.
 */
import { Radio, Route } from 'lucide-react'
import type { Module } from '@/audit/types'

export const MODULE_DEMAND: Module = {
  id: 'd3',
  number: '03',
  title: 'Where the business comes from',
  purpose:
    'Map every route a client arrives by, and what each one actually produces in enquiries, cost and settlements.',
  Icon: Radio,
  blocks: [
    {
      id: 'd3.map',
      title: 'The arrival map',
      intro:
        'Before we talk about marketing, I want the real mix. Not the campaigns, the arrivals. Let us build it from deals that settled.',
      questions: [
        {
          id: 'd3.routes-live',
          prompt:
            'Which of these are producing actual enquiries for you this month? Not ones you have tried, or intend to start. Live, this month.',
          kind: 'multi',
          why: 'Separates the routes they run from the routes they talk about. Sets the segmentation the build reads.',
          source: '99-source-material/snapshot/docs/03-custom-fields-approval-table.md',
          allowOther: true,
          choices: [
            { value: 'referral-past-client', label: 'Past client referrals' },
            { value: 'repeat-client', label: 'Repeat business from existing clients' },
            { value: 'real-estate-agent', label: 'Real estate agents' },
            { value: 'buyers-agent', label: 'Buyers agents' },
            { value: 'accountant', label: 'Accountants' },
            { value: 'financial-planner', label: 'Financial planners' },
            { value: 'builder-developer', label: 'Builders and developers' },
            { value: 'solicitor-conveyancer', label: 'Solicitors and conveyancers' },
            { value: 'website-form', label: 'Website enquiry form' },
            { value: 'google-organic', label: 'Google search, unpaid' },
            { value: 'google-ads', label: 'Google Ads' },
            { value: 'meta-ads', label: 'Meta or other paid social' },
            { value: 'social-organic', label: 'Organic social content' },
            {
              value: 'aggregator-leads',
              label: 'Leads from the aggregator',
              hint: 'Distributed to you rather than generated by you',
              flag: 'watch',
              flagNote:
                'Leads arriving through the aggregator raise an ownership question before a marketing one. Ask who holds the contact record and what happens to it if the aggregator relationship ends.',
            },
            {
              value: 'bought-leads',
              label: 'Bought leads',
              hint: 'Comparison sites, lead brokers, paid networks',
              flag: 'watch',
              flagNote:
                'Bought leads are often sold to more than one broker. Establish exclusivity, the consent record behind the contact, and what the client is paying per lead before any route economics are read.',
            },
            { value: 'walk-in', label: 'Walk-in or shopfront' },
            { value: 'events', label: 'Events and seminars' },
            { value: 'community', label: 'Community, sporting club, church, local network' },
            {
              value: 'cold-outreach',
              label: 'Cold outreach',
              hint: 'Cold email, cold calls, cold DMs',
              flag: 'risk',
              flagNote:
                'Cold outreach brings consent records, do-not-call washing and calling hours with it. Treat it as its own workstream with its own risk read, not as an extension of what already runs.',
            },
          ],
          followUp:
            'Of the ones you did not tick, which are switched on somewhere and producing nothing?',
        },
        {
          id: 'd3.route-mix',
          prompt:
            'Let us put numbers against them. For each route that is live: roughly how many enquiries a month, what it costs you a month, and how many of those settle.',
          kind: 'table',
          why: 'Turns the route list into economics. A route with cost and no settlements is the first thing to name.',
          hint: 'One row per live route. Leave a cell blank rather than guessing, and say out loud that it is blank.',
          source: '08-channels-and-playbooks/ads.md',
          columns: [
            { key: 'route', label: 'Route', kind: 'short', width: 'lg' },
            { key: 'enquiries', label: 'Enquiries / mo', kind: 'number', width: 'sm' },
            { key: 'cost', label: 'Cost / mo', kind: 'currency', width: 'sm' },
            { key: 'settled', label: 'Settled / mo', kind: 'number', width: 'sm' },
            { key: 'conversion', label: 'Enquiry to settled', kind: 'percent', width: 'sm' },
          ],
          flags: [
            {
              op: 'empty',
              level: 'watch',
              title: 'No route economics on the table',
              note: 'The client cannot put volume or cost against their own routes, so there is no baseline to build against and nothing to be measured on later.',
              action: 'Ask what they would have to open to work it out, and how long that would take.',
            },
          ],
        },
        {
          id: 'd3.last-ten',
          prompt:
            'Take me through the last ten deals you settled. Initials or a file reference, no client names. For each one, where did that person first arrive from? The first touch, not where it was finally attributed.',
          kind: 'table',
          why: 'Reconstructs the true mix from settled evidence instead of the channel narrative.',
          source: '03-audience-and-icp/buyer-psychology.md',
          columns: [
            { key: 'deal', label: 'Deal', kind: 'short', width: 'md' },
            { key: 'firstTouch', label: 'Where it actually started', kind: 'short', width: 'lg' },
            { key: 'referrer', label: 'Who referred, if anyone', kind: 'short', width: 'md' },
            { key: 'monthsAgo', label: 'Months ago', kind: 'number', width: 'sm' },
          ],
          followUp:
            'Of those ten, how many could you name the referrer for right now, without looking it up?',
          flags: [
            {
              op: 'empty',
              level: 'risk',
              title: 'The last ten cannot be reconstructed',
              note: 'No usable arrival history means no baseline, and a migration with no source of truth for where contacts came from.',
              action: 'Ask where those ten deals live today, and who would have to pull them.',
            },
          ],
        },
        {
          id: 'd3.source-capture',
          prompt: 'When an enquiry lands, where does the source get recorded?',
          kind: 'single',
          why: 'Free text cannot segment, route or report. This decides whether attribution is a build item or a tidy-up.',
          source: '11-operations/custom-fields.md',
          choices: [
            {
              value: 'structured-field',
              label: 'A set list of sources on the contact record',
              hint: 'Pick from a fixed list rather than typing',
            },
            {
              value: 'free-text',
              label: 'Typed into a text box or a note',
              flag: 'risk',
              flagNote:
                'Free text cannot be segmented, routed or reported on. Every variation is a separate value, so attribution has to be rebuilt by hand before anything can read it.',
            },
            {
              value: 'aggregator-only',
              label: 'Only in the aggregator system',
              flag: 'watch',
              flagNote:
                'Source lives where the marketing does not. Establish whether it can be exported, on what cadence, and who owns the export.',
            },
            {
              value: 'spreadsheet',
              label: 'A spreadsheet somebody maintains',
              flag: 'watch',
              flagNote:
                'A spreadsheet is a record, not a trigger. Nothing downstream can read it, and it stops the day the person maintaining it is busy.',
            },
            {
              value: 'not-recorded',
              label: 'It is not recorded anywhere',
              flag: 'risk',
              flagNote:
                'No arrival data at all. Attribution, routing and any later measurement all start from zero, and that has to be said plainly before any channel conversation.',
            },
          ],
        },
        {
          id: 'd3.cold-outbound',
          prompt: 'Do you run any cold outbound at all today, email, calls, DMs or LinkedIn?',
          kind: 'yesno',
          why: 'Decides whether we are extending something running or standing up a first motion, and it opens the consent workstream.',
          source: '07-compliance-and-guardrails/layer-a/spam-act-and-dnc.md',
          followUp:
            'What list, where did it come from, and what consent record sits behind each contact on it?',
          flags: [
            {
              op: 'eq',
              value: 'yes',
              level: 'risk',
              title: 'Cold outbound is running today',
              note: 'Consent records, do-not-call washing and calling hours all apply to that motion and they sit with the client. It is a separate workstream with its own risk read, and it needs their own advice rather than ours.',
              action: 'Ask to see the list source and the consent record before anything else is discussed about it.',
            },
          ],
        },
      ],
    },
    {
      id: 'd3.partners',
      title: 'Who sends you business',
      intro:
        'Referral is usually the strongest route in a brokerage and the least recorded. I want names, types and numbers.',
      questions: [
        {
          id: 'd3.partner-types',
          prompt: 'What types of referral partner are you working with?',
          kind: 'multi',
          why: 'Partner type is a structured value in the build, so capturing it here means the records load rather than needing mapping.',
          source: '99-source-material/snapshot/docs/03-custom-fields-approval-table.md',
          allowOther: true,
          choices: [
            { value: 'real-estate-agent', label: 'Real estate agent' },
            { value: 'buyers-agent', label: 'Buyers agent' },
            { value: 'accountant', label: 'Accountant' },
            { value: 'financial-planner', label: 'Financial planner' },
            { value: 'solicitor-conveyancer', label: 'Solicitor or conveyancer' },
            { value: 'builder', label: 'Builder' },
            { value: 'developer', label: 'Developer' },
            { value: 'other-broker', label: 'Another broker' },
            { value: 'past-clients', label: 'Past clients only, no professional partners' },
            {
              value: 'none',
              label: 'Nobody sends us business',
              flag: 'watch',
              flagNote:
                'The one arrival route with evidence behind it is absent from this business. Anything built there starts from nothing rather than extending something that works, and that has to be said out loud.',
            },
          ],
        },
        {
          id: 'd3.partner-table',
          prompt: 'Name them. Who sends you business, what kind, and how much did each send last year?',
          kind: 'table',
          why: 'Attribution is what turns referral from a feeling into a route with a number against it.',
          source: '99-source-material/snapshot/docs/12-wiring-map.md',
          columns: [
            { key: 'partner', label: 'Partner', kind: 'short', width: 'lg' },
            { key: 'type', label: 'Type', kind: 'short', width: 'md' },
            { key: 'deals12', label: 'Deals, 12 mo', kind: 'number', width: 'sm' },
            { key: 'lastReferral', label: 'Last referral', kind: 'short', width: 'sm' },
          ],
          followUp: 'Which of those has gone quiet, and do you know why?',
          flags: [
            {
              op: 'empty',
              level: 'risk',
              title: 'Partners cannot be named with volumes against them',
              note: 'A referral route with no record of who sends what cannot be rewarded, nurtured or reproduced, and it cannot be handed to anyone else in the business.',
              action: 'Ask who would know, and whether it is written anywhere or held in one head.',
            },
          ],
        },
        {
          id: 'd3.partner-rests-on',
          prompt:
            'Your strongest partner, the one who sends the most. What does that relationship actually rest on?',
          kind: 'single',
          why: 'Tells us whether the route survives a person leaving, and whether a reward arrangement is in play.',
          source: '03-audience-and-icp/persona-broker-ben-construct.md',
          choices: [
            {
              value: 'personal-relationship',
              label: 'A personal relationship with one person',
              flag: 'watch',
              flagNote:
                'The route leaves when that person does. Nothing in the business holds it, so it cannot be handed over or defended.',
            },
            { value: 'reciprocal', label: 'Reciprocal referrals, both ways' },
            { value: 'documented-agreement', label: 'A written referrer agreement' },
            {
              value: 'paid-arrangement',
              label: 'A paid or commission-sharing arrangement',
              flag: 'watch',
              flagNote:
                'Paid referral arrangements carry disclosure obligations that sit with the client, and any surface showing what a partner has earned is a third-party earnings surface. Note it and route it to their own adviser.',
            },
            { value: 'service-quality', label: 'The service their clients get back' },
            {
              value: 'not-sure',
              label: 'Honestly, not sure',
              flag: 'watch',
              flagNote:
                'If the client cannot say why the strongest route works, it cannot be deliberately repeated with a second partner.',
            },
          ],
        },
        {
          id: 'd3.partner-agreement',
          prompt: 'Is any of that written down, a referrer agreement or anything documented?',
          kind: 'yesno',
          why: 'Documented or not changes what can be tracked, paid and handed over.',
          source: '03-audience-and-icp/lexicon-industry-terms.md',
          flags: [
            {
              op: 'eq',
              value: 'no',
              level: 'watch',
              title: 'Referral arrangements are undocumented',
              note: 'Nothing defines what is owed, to whom, or on what event. Payouts rest on memory and the route cannot be handed to anyone else in the business.',
              action: 'Ask what has been promised verbally, and to whom.',
            },
          ],
        },
        {
          id: 'd3.partner-reward',
          prompt: 'Do you reward referrers, and how?',
          kind: 'multi',
          why: 'Reward shape decides what has to be tracked, and whether a disclosure question is in play.',
          source: '02-offer-and-pricing/micro-apps.md',
          allowOther: true,
          choices: [
            { value: 'gift-card', label: 'Gift card or a bottle' },
            {
              value: 'commission-share',
              label: 'A share of the commission',
              flag: 'watch',
              flagNote:
                'Commission sharing brings referral disclosure obligations, and they sit with the client. Record the arrangement and hand the question to their own adviser.',
            },
            { value: 'co-marketing', label: 'Co-marketing, events or content' },
            { value: 'charity-donation', label: 'A donation to their charity' },
            { value: 'reciprocal-referral', label: 'Referrals back to them' },
            {
              value: 'nothing-formal',
              label: 'Nothing formal',
              flag: 'watch',
              flagNote:
                'No reward means nothing to record, which is straightforward, but it also means there is no reason recorded anywhere for a partner to keep sending.',
            },
          ],
        },
      ],
    },
    {
      id: 'd3.paid',
      title: 'What you pay for, and what it costs',
      intro:
        'Now the money side. I want your figures, not industry ones, and blank is a perfectly good answer.',
      questions: [
        {
          id: 'd3.paid-status',
          prompt: 'Are you running any paid lead generation at the moment?',
          kind: 'single',
          why: 'Running, stopped and never-run are three different conversations and three different builds.',
          source: '03-audience-and-icp/voice-of-customer.md',
          choices: [
            { value: 'currently-running', label: 'Yes, running now' },
            {
              value: 'ran-turned-off',
              label: 'Ran it before, turned it off',
              flag: 'watch',
              flagNote:
                'Something stopped it. Whether it was cost, lead quality or capacity changes what the honest version of the conversation is.',
            },
            { value: 'never-run', label: 'Never run it' },
            {
              value: 'about-to-start',
              label: 'About to start',
              flag: 'watch',
              flagNote:
                'Turning on spend before the handling behind it exists is the sequence most likely to produce paid enquiries nobody answers. Ask what happens to the first fifty.',
            },
          ],
          followUp: 'If you turned it off, what stopped it. Cost, lead quality, or capacity?',
        },
        {
          id: 'd3.lead-buying',
          prompt: 'Do you buy leads from anyone, or pay to be on someone else’s list?',
          kind: 'multi',
          why: 'Bought leads carry exclusivity and consent questions the client owns.',
          source: '06-competitors-and-market/market-context.md',
          allowOther: true,
          choices: [
            { value: 'aggregator-lead-flow', label: 'Paid lead flow from the aggregator' },
            {
              value: 'comparison-site',
              label: 'A comparison or marketplace site',
              flag: 'watch',
              flagNote:
                'Marketplace leads are commonly sold to more than one broker. Establish exclusivity and the consent record behind each contact.',
            },
            {
              value: 'lead-broker',
              label: 'A lead broker or lead vendor',
              flag: 'watch',
              flagNote:
                'A purchased list brings someone else consent record with it, and that record is the client obligation once they contact the person.',
            },
            { value: 'group-or-franchise', label: 'Group or franchise lead allocation' },
            { value: 'directory-fee', label: 'A paid directory or panel listing' },
            { value: 'none', label: 'We do not buy leads' },
          ],
          followUp: 'What do you pay for each of those, per lead or per month?',
        },
        {
          id: 'd3.cost-per-lead',
          prompt: 'On the routes you pay for, what does one enquiry cost you?',
          kind: 'currency',
          why: 'The first half of the unit economics. Their figure, dated, theirs.',
          unit: 'per enquiry',
          source: '08-channels-and-playbooks/ads.md',
        },
        {
          id: 'd3.cost-per-settled',
          prompt: 'Have you ever worked out what a settled loan costs you to acquire?',
          kind: 'single',
          why: 'Whether they hold the number at all is the finding. The figure is second.',
          source: '05-proof-and-evidence/what-we-cannot-claim.md',
          choices: [
            { value: 'yes-know-number', label: 'Yes, I know the number' },
            { value: 'estimated', label: 'I have estimated it, roughly' },
            {
              value: 'never',
              label: 'Never worked it out',
              flag: 'opportunity',
              flagNote:
                'Without a cost per settled loan there is no way to compare one route to another, and no baseline to hold any later change against. Worth building before anything is switched on or off.',
            },
          ],
        },
        {
          id: 'd3.cost-per-settled-figure',
          prompt: 'What is it, all in?',
          kind: 'currency',
          why: 'The baseline any later comparison has to be measured against.',
          unit: 'per settled loan',
          source: '05-proof-and-evidence/what-we-cannot-claim.md',
          showIf: { question: 'd3.cost-per-settled', equals: ['yes-know-number', 'estimated'] },
        },
      ],
    },
    {
      id: 'd3.honest',
      title: 'What you wish worked, and what you stopped',
      intro:
        'Last part of this chapter, and usually the most useful. What have you tried, and what do you actually want?',
      questions: [
        {
          id: 'd3.demand-or-capacity',
          prompt:
            'Do you actually want more leads right now, or is the problem what happens after the lead arrives?',
          kind: 'single',
          why: 'The single most important split on the call. It decides which half of the conversation is the honest one.',
          source: '03-audience-and-icp/buyer-psychology.md',
          choices: [
            {
              value: 'more-leads',
              label: 'More leads',
              flag: 'watch',
              flagNote:
                'Lead volume is the weakest thing we can speak to. Say so plainly, and test whether the capacity conversation lands before going further.',
            },
            { value: 'after-arrival', label: 'What happens after the lead arrives' },
            { value: 'both', label: 'Both, and I know that is a lot' },
            { value: 'retention', label: 'Neither. It is holding on to the clients I have' },
          ],
          followUp: 'What makes you say that one and not the others?',
        },
        {
          id: 'd3.wish-worked',
          prompt: 'Which route do you wish worked, and does not?',
          kind: 'single',
          why: 'Names the thing they have already spent attention on. Usually where the last failed attempt is buried.',
          source: '08-channels-and-playbooks/funnels.md',
          allowOther: true,
          choices: [
            { value: 'website', label: 'The website' },
            { value: 'google', label: 'Google, paid or unpaid' },
            { value: 'paid-social', label: 'Paid social' },
            { value: 'organic-content', label: 'Organic content and video' },
            { value: 'real-estate-agents', label: 'Real estate agents' },
            { value: 'accountants-planners', label: 'Accountants and planners' },
            { value: 'past-client-referrals', label: 'Past client referrals' },
            { value: 'events-community', label: 'Events and community' },
            { value: 'database', label: 'The database I already have' },
          ],
          followUp: 'What did you try last time, and what happened?',
        },
        {
          id: 'd3.stopped',
          prompt: 'What have you stopped doing, and why did you stop?',
          kind: 'long',
          why: 'The graveyard. Anything rebuilt on top of a route they abandoned needs the reason it failed first.',
          placeholder:
            'Channels, agencies, tools, campaigns. What it cost, how long it ran, and what ended it.',
          source: '01-company/how-we-work.md',
        },
        {
          id: 'd3.registered-never-transacted',
          prompt:
            'How many people have registered or signed up with you and then never actually referred or transacted?',
          kind: 'number',
          why: 'Sizes the cheapest volume in the business. It is also the number most often unknown.',
          unit: 'contacts',
          source: '03-audience-and-icp/voice-of-customer-verbatim.md',
          flags: [
            {
              op: 'gt',
              value: 100,
              level: 'opportunity',
              title: 'A sizeable registered-but-dormant group',
              note: 'A group already known to the business and never activated. It is the first list worth sizing properly, and it belongs to the client rather than to any channel.',
              action: 'Ask where those records live today and whether they can be exported.',
            },
          ],
        },
      ],
    },
  ],
}

export const MODULE_JOURNEY: Module = {
  id: 'd4',
  number: '04',
  title: 'The customer journey',
  purpose:
    'Walk one real deal end to end, first touch to repeat business, and record what every step runs on and who holds it.',
  Icon: Route,
  blocks: [
    {
      id: 'd4.arrival',
      title: 'First touch, and the first hour',
      intro:
        'I want to walk one real deal with you, start to finish. We will go step by step, and at each step I will ask the same three things: what happens, who does it, and what it runs on.',
      questions: [
        {
          id: 'd4.first-touch',
          prompt:
            'A new enquiry lands right now, this minute. Walk me through the next hour. Who touches it, in what tool, and what do they actually do?',
          kind: 'long',
          why: 'The mechanism, not the intention. Everything in the first block attaches here.',
          placeholder: 'Follow one enquiry, minute by minute. Names and tools, not roles.',
          source: '11-operations/call-script-system.md',
        },
        {
          id: 'd4.speed-to-lead',
          prompt:
            'On your own numbers, how long from an enquiry landing to a human response? Your figure, not a target.',
          kind: 'number',
          why: 'Record their figure as theirs. There is no Australian measurement of broker response behaviour to hold it against, so we never quote one.',
          unit: 'minutes',
          hint: 'If they give a range, take the slower end and say that is what you are writing down.',
          source: '06-competitors-and-market/market-context.md',
          flags: [
            {
              op: 'gt',
              value: 240,
              level: 'watch',
              title: 'Response measured in hours',
              note: 'On the client own figure, an enquiry waits hours for a person. Record it as theirs, dated, and do not compare it to anything.',
              action: 'Ask what happens to an enquiry that lands at 4pm on a Friday.',
            },
            {
              op: 'gt',
              value: 1440,
              level: 'risk',
              title: 'Response measured in days',
              note: 'More than a day to a human response, on their own figure. Whatever sits upstream of that step is producing enquiries nobody is reaching.',
              action: 'Ask how many enquiries in the last month never got a call back at all.',
            },
          ],
        },
        {
          id: 'd4.after-hours',
          prompt: 'Who answers after hours and at the weekend?',
          kind: 'single',
          why: 'Names the person the work currently rests on, and whether there is any cover at all.',
          source: '11-operations/send-windows-and-rate-rules.md',
          choices: [
            {
              value: 'nobody-until-next-day',
              label: 'Nobody until the next business day',
              flag: 'watch',
              flagNote:
                'Everything arriving outside business hours waits. Worth knowing what share of enquiries that is before deciding whether it matters.',
            },
            {
              value: 'broker-mobile',
              label: 'It goes to the broker mobile, whatever the hour',
              flag: 'watch',
              flagNote:
                'The cover is one person, and it is the same person the rest of this conversation is about taking work off. Note the hours they are actually on.',
            },
            { value: 'answering-service', label: 'A receptionist or answering service' },
            { value: 'auto-reply', label: 'An automatic reply, then a person next day' },
            { value: 'chat-or-assistant', label: 'A chat or assistant handles the first response' },
            {
              value: 'not-sure',
              label: 'Not sure, honestly',
              flag: 'watch',
              flagNote:
                'Nobody in the business knows what happens to an out-of-hours enquiry, which means nobody knows how many there are.',
            },
          ],
          followUp:
            'Name the person who owns the phone ringing, and tell me what else they do all day.',
        },
        {
          id: 'd4.enquiry-landing',
          prompt: 'A website enquiry. Where does it physically land?',
          kind: 'single',
          why: 'Decides whether there is a record to build on, and who owns it.',
          source: '03-audience-and-icp/voice-of-customer.md',
          choices: [
            {
              value: 'aggregator-crm',
              label: 'In the aggregator system',
              flag: 'watch',
              flagNote:
                'The enquiry lands where the marketing does not. Establish who owns that contact record and what leaves with the client if the aggregator relationship changes.',
            },
            {
              value: 'email-inbox',
              label: 'An email inbox',
              flag: 'watch',
              flagNote:
                'An inbox is not a record. Nothing can route from it, nothing can report on it, and it is read by whoever happens to be looking.',
            },
            { value: 'separate-crm', label: 'A separate CRM we control' },
            {
              value: 'spreadsheet',
              label: 'A spreadsheet somebody copies it into',
              flag: 'risk',
              flagNote:
                'A manual copy step between arrival and record. Every enquiry that arrives while that person is busy is an enquiry with no record at all.',
            },
            { value: 'phone-only', label: 'There is no form. They ring us' },
            {
              value: 'nowhere',
              label: 'Nowhere, really',
              flag: 'risk',
              flagNote:
                'Enquiries arrive and leave no record. There is no baseline, no follow-up trail, and no way to know what has been missed.',
            },
          ],
        },
        {
          id: 'd4.qualify-step',
          prompt:
            'Between that first response and you treating it as a real deal, what has to be true, and who decides?',
          kind: 'long',
          why: 'Finds the qualification step, and whether it exists as a rule or as one person judgement.',
          placeholder: 'What gets asked, what gets checked, and who calls it either way.',
          source: '11-operations/pipelines-and-stages.md',
        },
        {
          id: 'd4.no-convert',
          prompt: 'What happens to an enquiry that does not convert?',
          kind: 'single',
          why: 'The largest unattended group in most brokerages, and the one the client can size.',
          source: '11-operations/sequence-architecture.md',
          allowOther: true,
          choices: [
            {
              value: 'nothing',
              label: 'Nothing. It just sits there',
              flag: 'risk',
              flagNote:
                'Enquiries the business already paid for, in time or money, with nothing attached to them. Size the group before discussing anything else about it.',
            },
            {
              value: 'manual-when-remembered',
              label: 'Someone follows up when they remember',
              flag: 'risk',
              flagNote:
                'Follow-up depends on recall, so it happens in quiet weeks and stops in busy ones, which is the opposite of when it is needed.',
            },
            {
              value: 'tagged-archived',
              label: 'Tagged and archived',
              flag: 'watch',
              flagNote:
                'There is a record, which is more than most. Establish whether anything ever reads that tag again.',
            },
            { value: 'nurture-sequence', label: 'It goes into a nurture sequence' },
            { value: 'diarised-callback', label: 'A diarised call-back with a date on it' },
          ],
          followUp: 'Roughly how many are sitting in that state right now?',
        },
      ],
    },
    {
      id: 'd4.prepare',
      title: 'Credit guide, fact find, documents',
      intro:
        'This is the part of the journey with the most steps and the least visibility. I am recording what you do, not ruling on it.',
      questions: [
        {
          id: 'd4.credit-guide-timing',
          prompt: 'At what point does the credit guide go out?',
          kind: 'single',
          why: 'Compliance-sensitive step. The obligation turns on a likelihood test (NCCP s113), so it can fall due before a product is named. Record the practice, do not rule on it.',
          hint: 'Their answer is a description of what they do. If it looks late, note it and route it to their own adviser rather than calling it.',
          source: '07-compliance-and-guardrails/layer-b/credit-guide-timing-s113.md',
          choices: [
            { value: 'at-first-enquiry', label: 'At the first enquiry, before anything else' },
            { value: 'before-first-conversation', label: 'Before the first real conversation' },
            {
              value: 'at-fact-find',
              label: 'At the fact find',
              flag: 'watch',
              flagNote:
                'The obligation turns on when credit assistance becomes likely, which can be earlier than the fact find. Note the timing and hand the question to whoever advises them on it.',
            },
            {
              value: 'when-product-discussed',
              label: 'When we start talking about a specific product',
              flag: 'watch',
              flagNote:
                'The trigger is a likelihood test rather than the naming of a product, so this ordering is worth their adviser looking at. Record it and move on.',
            },
            {
              value: 'at-application',
              label: 'With the application paperwork',
              flag: 'watch',
              flagNote:
                'Sits near the end of the process, and the obligation arises earlier than that. Note it, do not diagnose it, and route it to their own adviser.',
            },
            {
              value: 'varies-by-broker',
              label: 'It varies by who is handling it',
              flag: 'watch',
              flagNote:
                'No single practice across the business, so there is nothing consistent to evidence and nothing consistent to hand over.',
            },
            {
              value: 'not-sure',
              label: 'Not sure',
              flag: 'risk',
              flagNote:
                'Nobody on the call can say when it goes out. That is a question for their own adviser before it is a question for any build.',
            },
          ],
        },
        {
          id: 'd4.credit-guide-record',
          prompt: 'And how do you know it went, and when?',
          kind: 'single',
          why: 'Compliance-sensitive. A stage moving is not evidence that anything was sent or received.',
          source: '07-compliance-and-guardrails/layer-c/bid-by-construction.md',
          choices: [
            { value: 'acknowledged-record', label: 'A signed or acknowledged record on the file' },
            {
              value: 'email-in-thread',
              label: 'The email is in the thread somewhere',
              flag: 'watch',
              flagNote:
                'Retrievable, but only by the person who knows where to look, and only while that mailbox exists.',
            },
            {
              value: 'crm-stage-moved',
              label: 'A stage gets moved in the system',
              flag: 'risk',
              flagNote:
                'A stage transition records that somebody moved a card. It does not record that the guide was sent, or when, or that it arrived. Worth saying plainly and routing to their own adviser.',
            },
            {
              value: 'no-record',
              label: 'There is no record of it',
              flag: 'risk',
              flagNote:
                'Nothing evidences the step. That is their exposure to carry and their adviser to answer, and it is also the clearest thing on the whiteboard today.',
            },
            {
              value: 'not-sure',
              label: 'Not sure',
              flag: 'risk',
              flagNote:
                'If nobody can say where the record is, treat it as absent until somebody shows it.',
            },
          ],
        },
        {
          id: 'd4.fact-find',
          prompt: 'Where does the fact find happen today, and what does it run on?',
          kind: 'long',
          why: 'One of the parts of the day a build actually touches. Get the tool and the handover, not the form.',
          placeholder: 'In person, on a call, on a form. What the client fills in and what gets rekeyed.',
          source: '03-audience-and-icp/lexicon-industry-terms.md',
        },
        {
          id: 'd4.docs-collection',
          prompt: 'Document collection. What does that actually run on?',
          kind: 'single',
          why: 'The longest step in most brokerages and the one with the most manual chasing.',
          source: '11-operations/workflows.md',
          choices: [
            {
              value: 'email-back-and-forth',
              label: 'Email, back and forth',
              flag: 'watch',
              flagNote:
                'No state anywhere. What is outstanding lives in whoever last read the thread, so nothing can chase on its own.',
            },
            {
              value: 'sms-and-photos',
              label: 'Texts and photos',
              flag: 'watch',
              flagNote:
                'Documents arriving on a personal phone are outside every record the business keeps. Note where they end up afterwards.',
            },
            { value: 'client-portal', label: 'A client portal with a checklist' },
            { value: 'aggregator-upload', label: 'The aggregator document upload' },
            { value: 'shared-drive', label: 'A shared drive folder per client' },
            {
              value: 'mixed-no-standard',
              label: 'All of the above, depending on the client',
              flag: 'risk',
              flagNote:
                'No standard means no single place to look, and the person covering a file cannot tell what is outstanding without asking.',
            },
          ],
        },
        {
          id: 'd4.docs-chase-hours',
          prompt: 'How many hours a deal goes into chasing documents, on your own estimate?',
          kind: 'number',
          why: 'Their figure, theirs alone. We never publish or reuse it as a benchmark.',
          unit: 'hours per deal',
          source: '11-operations/current-build-state.md',
          flags: [
            {
              op: 'gt',
              value: 4,
              level: 'opportunity',
              title: 'Document chasing is a large manual block',
              note: 'On the client own estimate, several hours a deal go into chasing. Record the figure as theirs and dated. Do not convert it into a saving, a dollar figure or a projection.',
              action: 'Ask who does those hours, and what they are not doing while they do them.',
            },
          ],
        },
        {
          id: 'd4.serviceability-tool',
          prompt: 'Where does serviceability get worked out, and by whom?',
          kind: 'single',
          why: 'Marks the boundary. Calculation and credit assessment stay with the broker and the aggregator.',
          source: '02-offer-and-pricing/boundaries.md',
          choices: [
            { value: 'aggregator-calculator', label: 'The aggregator servicing calculator' },
            { value: 'lender-calculators', label: 'Individual lender calculators' },
            {
              value: 'own-spreadsheet',
              label: 'Our own spreadsheet',
              flag: 'watch',
              flagNote:
                'A private calculation tool that one person maintains and nobody has reviewed. Note who owns it and who checks it.',
            },
            {
              value: 'in-head',
              label: 'The broker does it in their head first, then checks',
              flag: 'watch',
              flagNote:
                'The first pass leaves no record, so nothing downstream can see why a deal was or was not progressed.',
            },
            { value: 'loan-processor', label: 'A loan processor or support person does it' },
            { value: 'mixed', label: 'A mix, depending on the lender' },
          ],
        },
        {
          id: 'd4.options-record',
          prompt:
            'When you present options and recommend one, where does the reasoning get written down, and what does the client actually get?',
          kind: 'long',
          why: 'Compliance-sensitive. This is where Best Interests Duty evidence belongs. Record what exists; do not rule on whether it is enough.',
          placeholder:
            'What is shown, what is kept, and where the reason for the recommendation is recorded.',
          hint: 'If the answer is that it lives in the broker head or in a phone call, write that down plainly and move on.',
          source: '07-compliance-and-guardrails/layer-b/best-interests-duty-rg273.md',
        },
      ],
    },
    {
      id: 'd4.deal',
      title: 'Submission to settlement',
      intro:
        'From the point the deal is real through to the day it settles. Same three questions at each step.',
      questions: [
        {
          id: 'd4.submission-step',
          prompt:
            'From the deal qualifying to lodgement. What happens, who does it, and where does it sit while it is happening?',
          kind: 'long',
          why: 'Finds the handover points, which is where deals go quiet.',
          placeholder: 'Packaging, lodgement, who keys it, and what the client is told at each point.',
          source: '11-operations/pipelines-and-stages.md',
        },
        {
          id: 'd4.lodgement-days',
          prompt: 'Typical days from the fact find being complete to lodgement?',
          kind: 'number',
          why: 'Their number. The gap between this and their expectation is usually where the frustration sits.',
          unit: 'days',
          source: '11-operations/pipelines-and-stages.md',
        },
        {
          id: 'd4.settle-days',
          prompt: 'And typical days from submission to settlement?',
          kind: 'number',
          why: 'Sets the length of the window the client has to be kept informed across.',
          unit: 'days',
          source: '11-operations/pipelines-and-stages.md',
        },
        {
          id: 'd4.status-updates',
          prompt: 'What triggers a client update between lodgement and settlement?',
          kind: 'single',
          why: 'Keeping clients informed well enough that they stop ringing is one of the two motives on file from a paying buyer.',
          source: '03-audience-and-icp/buyer-psychology.md',
          allowOther: true,
          choices: [
            {
              value: 'lender-email',
              label: 'A lender email arrives and we forward it on',
              flag: 'watch',
              flagNote:
                'The update depends on somebody reading the mailbox that day. Quiet from the lender reads to the client as quiet from the broker.',
            },
            { value: 'diarised-check', label: 'A diarised check, whether or not there is news' },
            {
              value: 'client-rings',
              label: 'The client rings and asks',
              flag: 'risk',
              flagNote:
                'The client is doing the follow-up, which makes the client the trigger rather than the process. It is measurable by counting the calls.',
            },
            { value: 'stage-change', label: 'It goes out automatically when the stage changes' },
            {
              value: 'nothing-systematic',
              label: 'Nothing systematic',
              flag: 'risk',
              flagNote:
                'The longest stretch of the journey has no contact rule behind it, so what the client hears depends entirely on who is handling it.',
            },
          ],
          followUp: 'How often does a client ring you to ask where it is at?',
        },
        {
          id: 'd4.milestones-stamped',
          prompt:
            'Which of these get stamped as an actual date on the client record, in a date field rather than a note?',
          kind: 'multi',
          why: 'Every downstream trigger reads a date. A date held as text or in a note cannot fire anything, and field type is permanent once set.',
          source: '11-operations/custom-fields.md',
          allowOther: true,
          choices: [
            { value: 'conditional-approval', label: 'Conditional approval' },
            { value: 'formal-approval', label: 'Formal approval' },
            { value: 'docs-issued', label: 'Documents issued' },
            { value: 'settlement-booked', label: 'Settlement booked' },
            { value: 'settlement-date', label: 'Settlement date' },
            { value: 'fixed-rate-expiry', label: 'Fixed rate expiry' },
            { value: 'annual-review-due', label: 'Annual review due' },
            {
              value: 'none',
              label: 'None of them, as a date field',
              flag: 'risk',
              flagNote:
                'Nothing downstream has a date to read. Anything built to fire on one of these would sit there looking configured and never run, which is the failure that is hardest to notice.',
            },
          ],
          followUp: 'And where do those dates live. Which system, and who types them in?',
        },
        {
          id: 'd4.one-head',
          prompt:
            'Auditor read: how much of everything we have just walked through runs in one person head?',
          kind: 'scale',
          why: 'Your judgement, not theirs. This is the number the handover conversation later rests on.',
          min: 1,
          max: 5,
          scaleLabels: ['Written down, anyone could run it', 'Entirely in one head'],
          source: '11-operations/current-build-state.md',
          flags: [
            {
              op: 'gt',
              value: 3,
              level: 'risk',
              title: 'The process is held by one person',
              note: 'Most of the journey has no written form, so it cannot be delegated, covered during leave, or handed to a new hire without that person sitting beside them.',
              action: 'Ask what happens to a deal in progress if that person is away for two weeks.',
            },
          ],
        },
      ],
    },
    {
      id: 'd4.after',
      title: 'After settlement',
      intro:
        'Settlement is where most brokerages stop and where the book is made. Take me past it.',
      questions: [
        {
          id: 'd4.day-after',
          prompt: 'Keep going with that same deal. Once it settled, what happened next?',
          kind: 'long',
          why: 'Establishes whether a post-settlement motion exists at all. Usually the dimension that decides the sale.',
          placeholder: 'What the client gets, who sends it, and what gets recorded on the file.',
          source: '03-audience-and-icp/lexicon-industry-terms.md',
        },
        {
          id: 'd4.settlement-date-field',
          prompt: 'Is the settlement date recorded, and where?',
          kind: 'single',
          why: 'Everything after settlement keys off it: the referral ask, the anniversary, the annual review, the fixed rate window and clawback exposure.',
          source: '11-operations/call-script-system.md',
          choices: [
            { value: 'date-field-crm', label: 'A date field on the client record' },
            {
              value: 'spreadsheet',
              label: 'In a spreadsheet',
              flag: 'risk',
              flagNote:
                'A spreadsheet holds the date but cannot trigger anything from it. Every post-settlement step stays manual and depends on somebody opening the file.',
            },
            {
              value: 'aggregator-only',
              label: 'Only in the aggregator system',
              flag: 'watch',
              flagNote:
                'The date exists where nothing client-facing can read it. Establish whether it exports, how often, and who owns the export.',
            },
            {
              value: 'note-or-email',
              label: 'In a note or an email somewhere',
              flag: 'risk',
              flagNote:
                'A date held as text cannot drive a reminder. Field type is permanent once set, so this is a migration decision rather than a tidy-up.',
            },
            {
              value: 'not-recorded',
              label: 'Not recorded anywhere',
              flag: 'risk',
              flagNote:
                'Without a settlement date the entire post-settlement layer has nothing to fire from, and no anniversary, review or fixed-rate trigger can exist.',
            },
          ],
        },
        {
          id: 'd4.twelve-months',
          prompt: 'Twelve months after settlement. What does that client hear from you?',
          kind: 'single',
          why: 'The step most often described as never getting done.',
          source: '99-source-material/snapshot/docs/12-wiring-map.md',
          choices: [
            { value: 'annual-review-booked', label: 'An annual review, booked in' },
            {
              value: 'newsletter-only',
              label: 'The newsletter, same as everyone',
              flag: 'watch',
              flagNote:
                'Contact exists but it is undifferentiated. A client at a review point gets the same message as a client who settled last week.',
            },
            {
              value: 'anniversary-note',
              label: 'A card or an anniversary note',
              flag: 'watch',
              flagNote:
                'Contact without a conversation attached. It keeps the name alive and produces nothing on its own.',
            },
            {
              value: 'nothing',
              label: 'Honestly, nothing',
              flag: 'risk',
              flagNote:
                'A settled client hears nothing at the point they are most likely to be looking. Size the group and note it; do not promise a retention outcome.',
            },
            {
              value: 'depends-on-broker',
              label: 'Depends which broker settled it',
              flag: 'watch',
              flagNote:
                'The client experience after settlement varies by who handled the deal, so there is no business standard to hand over or improve against.',
            },
          ],
        },
        {
          id: 'd4.review-triggers',
          prompt: 'What actually triggers you to go back to a past client?',
          kind: 'multi',
          why: 'Compliance-sensitive. A rate or fixed-expiry trigger is not itself the issue, but what gets sent on it may sit inside the regulated perimeter, because suggesting a consumer act on a particular credit contract is credit assistance.',
          hint: 'Record what they do. The perimeter question is for their own adviser, not for this call.',
          source: '07-compliance-and-guardrails/layer-b/nccp-credit-activity-and-assistance.md',
          allowOther: true,
          choices: [
            { value: 'fixed-rate-expiry', label: 'Fixed rate expiry coming up' },
            { value: 'annual-review', label: 'An annual review date' },
            { value: 'rate-movement', label: 'A rate movement in the market' },
            { value: 'settlement-anniversary', label: 'The settlement anniversary' },
            { value: 'life-event', label: 'A life event we happen to hear about' },
            {
              value: 'client-rings',
              label: 'They ring us',
              flag: 'watch',
              flagNote:
                'Contact is client-initiated, so the ones who go quiet are the ones who go elsewhere, and nothing in the business notices.',
            },
            {
              value: 'nothing-systematic',
              label: 'Nothing systematic',
              flag: 'risk',
              flagNote:
                'No trigger of any kind after settlement. The book is a list rather than a route, and that is the clearest gap on the board today.',
            },
          ],
        },
        {
          id: 'd4.fixed-expiry-visibility',
          prompt:
            'Can you tell me today which of your clients roll off a fixed rate this quarter?',
          kind: 'single',
          why: 'The sharpest test of whether the date layer exists. Asked as a capability question, not a compliance one.',
          source: '99-source-material/snapshot/docs/12-wiring-map.md',
          choices: [
            { value: 'yes-list', label: 'Yes, I can pull the list now' },
            {
              value: 'yes-would-dig',
              label: 'Yes, but I would have to dig for it',
              flag: 'watch',
              flagNote:
                'The information exists but not in a form anything can act on. In practice it gets pulled when someone remembers to ask for it.',
            },
            {
              value: 'no',
              label: 'No',
              flag: 'risk',
              flagNote:
                'Fixed rate expiries are invisible to the business. Clients reach that point and nobody knows, which is the highest-value gap in the date layer.',
            },
            {
              value: 'not-tracked',
              label: 'We do not track fixed rates at all',
              flag: 'risk',
              flagNote:
                'Nothing records the rate type or the expiry, so there is no date to build from and no way to size the group without going back to the lenders.',
            },
          ],
          followUp: 'Roughly how many is that, over the next twelve months?',
        },
        {
          id: 'd4.stay-put-copy',
          prompt:
            'Does anything you send a past client ever tell them their current loan is fine, still competitive, or that there is no need to look at it?',
          kind: 'yesno',
          why: 'Compliance-sensitive. Suggesting a consumer remain in a particular credit contract falls inside credit assistance. Note it; do not rule on it.',
          source: '07-compliance-and-guardrails/layer-c/template-compliance-gate.md',
          flags: [
            {
              op: 'eq',
              value: 'yes',
              level: 'risk',
              title: 'Stay-put wording is going out to past clients',
              note: 'Wording that tells a borrower their existing loan is fine may sit inside the regulated perimeter. This is theirs to carry and theirs to take advice on. Record the wording, do not rule on it, and do not describe it as a breach.',
              action: 'Ask to see the exact wording and who signs it off before it goes.',
            },
          ],
        },
        {
          id: 'd4.repeat-deals',
          prompt:
            'How many of last year’s deals were repeat or refinance business from an existing client?',
          kind: 'number',
          why: 'The honest measure of whether the post-settlement layer works today, and the baseline any later change is read against.',
          unit: 'in the last 12 months',
          source: '05-proof-and-evidence/what-we-cannot-claim.md',
        },
        {
          id: 'd4.referral-ask',
          prompt: 'How do you ask a past client for a referral, and when?',
          kind: 'long',
          why: 'Referral is the one arrival route with evidence behind it. If the ask is unwritten it does not survive the person who makes it.',
          placeholder: 'The words used, who says them, and at what point after settlement.',
          source: '03-audience-and-icp/persona-broker-ben-construct.md',
          followUp: 'Is that written down anywhere, or is it in your head?',
        },
      ],
    },
  ],
}
